version: "3.6"

volumes:
  redis_data_med:
    name: redis_data_med
  postgres_data_med:
    name: postgres_data_med

services:
  postgres_med:
    image: postgres:13.0
    container_name: postgres_med
    restart: always
    volumes:
      - postgres_data_med:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - med

  redis_med:
    image: redis:6.2.6-bullseye
    container_name: redis_med
    restart: always
    volumes:
     - redis_data_med:/data
    depends_on:
      - postgres_med
    networks:
     - med

  med_api:
    build: .
    container_name: med_api
    depends_on:
      - postgres_med
    networks:
      - med
    env_file:
      - .env

  med_nginx:
    image: nginx:1.19.2
    container_name: med_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    depends_on:
      - med_api
    networks:
      - med


networks:
  med:
    driver: bridge