"""metrics

Revision ID: 15415484499f
Revises: 668812e1e544
Create Date: 2022-01-25 13:20:19.518303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15415484499f'
down_revision = '668812e1e544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__jwt__id'), 'jwt', ['id'])
    op.create_unique_constraint(op.f('uq__logins__id'), 'logins', ['id'])
    op.create_unique_constraint(op.f('uq__metric_data__id'), 'metric_data', ['id'])
    op.create_unique_constraint(op.f('uq__metric_results__id'), 'metric_results', ['id'])
    op.create_unique_constraint(op.f('uq__metric_users__id'), 'metric_users', ['id'])
    op.drop_constraint('uq__metrics__metric_name', 'metrics', type_='unique')
    op.create_unique_constraint(op.f('uq__metrics__id'), 'metrics', ['id'])
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq__metrics__id'), 'metrics', type_='unique')
    op.create_unique_constraint('uq__metrics__metric_name', 'metrics', ['metric_name'])
    op.drop_constraint(op.f('uq__metric_users__id'), 'metric_users', type_='unique')
    op.drop_constraint(op.f('uq__metric_results__id'), 'metric_results', type_='unique')
    op.drop_constraint(op.f('uq__metric_data__id'), 'metric_data', type_='unique')
    op.drop_constraint(op.f('uq__logins__id'), 'logins', type_='unique')
    op.drop_constraint(op.f('uq__jwt__id'), 'jwt', type_='unique')
    # ### end Alembic commands ###
